name: Project 4

on: [push]

jobs:

  build:

    name: Rust
    runs-on: ubuntu-latest
    timeout-minutes: 6

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1

      - name: Build Rust project
        run: cargo build --verbose

      - name: Run unit tests
        run: cargo tests --verbose
